import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          'TicketID': 'Ticket ID',
          'CreatedDateTime': 'Created Date & Time',
          'Department': 'Department',
          'SubDepartment': 'Sub Department',
          'Category': 'Category',
          'Priority': 'Priority',
          'Subject': 'Subject',
          'Description': 'Description',
          'Status': 'Status',
          'Hello': 'Hello',
          'TrackYourCamplaint': 'Track Your Camplaint',
          'EnteryourticketID': 'Enter your ticket ID',
          'OverallTickets': 'Overall Tickets',
          'PendingTickets': 'Pending Tickets\n( Not process yet )',
          'InProgressTickets': 'In Progress\nTickets',
          'CancelTickets': 'Cancel Tickets',
          'Completed': 'Completed',
          'Tickets': 'Tickets',
          'MyTickets': 'My Tickets',
          'From': 'From',
          'To': 'To',
          'Cancel': 'Cancel',
          'InProgress': 'In Progress',
          'Pending': 'Pending',
          'Overall': 'Overall',
          'selectLanguage': 'Select Language',
          'Ok': 'Ok',
          'biometric': 'Biometric',
          'languages': 'Languages',
          'PrivacyPolicy': 'Privacy Policy',
          'TermsConditions': 'Terms & Conditions',
          'logout': 'Logout',
          'welcomescreentext':
              'Such a system helps in addressing customer issues,\n improving customer satisfaction, and maintaining \n a positive reputation.',
          'LetsGo': "Let's Go",
          'WhatsAppisnotinstalledonyourdevice':
              'WhatsApp is not installed on your device.',
          'Home': 'Home',
          'AddTicket': 'Add Ticket',
          'Profile': 'Profile',
          'Help': 'Help',
          'SelectDepartment': 'Select Department',
          'SelectSubDepartment': 'Select Sub Department',
          'SelectCategory': 'Select Category',
          'SelectPriority': 'Select Priority',
          'AttachFile': 'Attach File',
          'Update': 'Update',
          'Name': 'Name',
          'DateofBirth': 'Date of Birth',
          'ContactNo': 'Contact No',
          'Email': 'Email',
          'Country': 'Country',
          'ProvinceState': 'Province/State',
          'City': 'City',
          'EditProfile': 'Edit Profile',
          'pleaseenteryourname': 'Please Enter Your Name',
          'pleaseenteryourcontactno': 'Please Enter Your Contact No',
          'pleaseenteryouremail': 'Please Enter Your Email',
          'pleaseselectyourcountry': 'Please Select Your Country',
          'pleaseselectyourprovince': 'Please Select Your Province',
          'pleaseselectyourcity': 'Please Select Your City',
          'PleasegivestoragePermissiontoapplication':
              'Please give storage permission to application',
          'Somethingwentwrong': 'Something went wrong',
        },
        "ar_SA": {
          'TicketID': 'رقم التذكرة',
          'CreatedDateTime': 'تاريخ ووقت الإنشاء',
          'Department': 'القسم',
          'SubDepartment': 'القسم الفرعي',
          'Category': 'الفئة',
          'Priority': 'الأولوية',
          'Subject': 'الموضوع',
          'Description': 'الوصف',
          'Status': 'الحالة',
          'Hello': 'مرحبًا',
          'TrackYourCamplaint': 'تتبع شكواك',
          'EnteryourticketID': 'أدخل معرف التذكرة الخاص بك',
          'OverallTickets': 'مجموع التذاكر',
          'PendingTickets': 'التذاكر المعلقة\n(لم يتم معالجتها بعد)',
          'InProgressTickets': 'التذاكر قيد التنفيذ',
          'CancelTickets': 'إلغاء التذاكر',
          'Completed': 'تم الانتهاء',
          'Tickets': 'تذاكر',
          'MyTickets': 'تذاكري',
          'From': 'من',
          'To': 'إلى',
          'Cancel': 'إلغاء',
          'InProgress': 'قيد التنفيذ',
          'Pending': 'قيد الانتظار',
          'Overall': 'بشكل عام',
          'selectLanguage': 'اختر اللغة',
          'Ok': 'حسنًا',
          'biometric': 'البيومتري',
          'languages': 'اللغات',
          'PrivacyPolicy': 'سياسة الخصوصية',
          'TermsConditions': 'الشروط والأحكام',
          'logout': 'تسجيل الخروج',
          'welcomescreentext':
              'يساعد هذا النظام في التعامل مع قضايا العملاء، تحسين رضا العملاء، والحفاظ على سمعة إيجابية.',
          'LetsGo': 'لنذهب',
          'WhatsAppisnotinstalledonyourdevice':
              'لم يتم تثبيت تطبيق واتساب على جهازك.',
          'Home': 'الرئيسية',
          'AddTicket': 'إضافة تذكرة',
          'Profile': 'الملف الشخصي',
          'Help': 'مساعدة',
          'SelectDepartment': 'اختر القسم',
          'SelectSubDepartment': 'اختر القسم الفرعي',
          'SelectCategory': 'اختر الفئة',
          'SelectPriority': 'اختر الأولوية',
          'AttachFile': 'إرفاق ملف',
          'Update': 'تحديث',
          'Name': 'اسم',
          'DateofBirth': 'تاريخ الميلاد',
          'ContactNo': 'رقم الاتصال',
          'Email': 'البريد الإلكتروني',
          'Country': 'الدولة',
          'ProvinceState': 'المقاطعة/الولاية',
          'City': 'المدينة',
          'EditProfile': 'تعديل الملف الشخصي',
          'pleaseenteryourname': 'الرجاء إدخال اسمك',
          'pleaseenteryourcontactno': 'الرجاء إدخال رقم الاتصال الخاص بك',
          'pleaseenteryouremail': 'الرجاء إدخال بريدك الإلكتروني',
          'pleaseselectyourcountry': 'الرجاء اختيار بلدك',
          'pleaseselectyourprovince': 'الرجاء اختيار مقاطعتك/ولايتك',
          'pleaseselectyourcity': 'الرجاء اختيار مدينتك',
          'PleasegivestoragePermissiontoapplication':
              'يرجى منح إذن التخزين للتطبيق',
          'Somethingwentwrong': 'حدث خطأ ما',
        },
        "ur_PK": {
          'TicketID': 'ٹکٹ آئی ڈی',
          'CreatedDateTime': 'تخلیق شدہ تاریخ و وقت',
          'Department': ' ڈیپارٹمنٹ',
          'SubDepartment': 'ذیلی ڈپارٹمنٹ',
          'Category': 'کیٹیگری',
          'Priority': 'ترتیب',
          'Subject': 'مضمون',
          'Description': 'تفصیل',
          'Status': 'حالت',
          'Hello': 'ہیلو',
          'TrackYourCamplaint': 'اپنی شکایت کا پیشہ ورزی کریں',
          'EnteryourticketID': 'اپنا ٹکٹ آئی ڈی درج کریں',
          'OverallTickets': 'کل ٹکٹس',
          'PendingTickets': 'زیر پروسیس ٹکٹس\n(عملدرآمد نہیں ہوئیں)',
          'InProgressTickets': 'عمل میں لانے کے لئے ٹکٹس',
          'CancelTickets': 'ٹکٹ منسوخ',
          'Completed': 'مکمل ',
          'Tickets': 'ٹکٹس',
          'MyTickets': 'میری ٹکٹس',
          'From': 'سے',
          'To': 'تک',
          'Cancel': 'منسوخ کریں',
          'InProgress': 'جاری ہے',
          'Pending': 'زیر التواء',
          'Overall': 'کل میں',
          'selectLanguage': 'زبان منتخب کریں',
          'Ok': 'ٹھیک ہے',
          'biometric': 'بائیومیٹرک',
          'languages': 'زبانیں',
          'PrivacyPolicy': 'رازداری کی پالیسی',
          'TermsConditions': 'شرائط و ضوابط',
          'logout': 'لاگ آؤٹ',
          'welcomescreentext':
              'ایسے ایک نظام میں مشغول ہونا، صارفین کے مسائل کا حل کرنے میں مدد فراہم کرتا ہے، صارفین کی خوشی میں بہتری کرتا ہے، اور ایک مثبت عہد بنائی رکھتا ہے۔',
          'LetsGo': 'چلو چلیں',
          'WhatsAppisnotinstalledonyourdevice':
              'آپ کے ڈیوائس پر واٹس ایپ انسٹال نہیں ہے۔',
          'Home': 'ہوم',
          'AddTicket': 'ٹکٹ شامل کریں',
          'Profile': 'پروفائل',
          'Help': 'مدد',
          'SelectDepartment': 'محکمہ منتخب کریں',
          'SelectSubDepartment': 'ذیلی محکمہ منتخب کریں',
          'SelectCategory': 'زمرہ منتخب کریں',
          'SelectPriority': 'ترجیح منتخب کریں',
          'AttachFile': 'فائل منسلک کریں',
          'Update': 'تازہ کاری',
          'Name': 'نام',
          'DateofBirth': 'تاریخ پیدائش',
          'ContactNo': 'رابطہ نمبر',
          'Email': 'ایمیل',
          'Country': 'ملک',
          'ProvinceState': 'صوبہ/ریاست',
          'City': 'شہر',
          'EditProfile': 'پروفائل میں ترتیب دیں',
          'pleaseenteryourname': 'براہ کرم اپنا نام درج کریں',
          'pleaseenteryourcontactno': 'براہ کرم اپنا رابطہ نمبر درج کریں',
          'pleaseenteryouremail': 'براہ کرم اپنا ایمیل درج کریں',
          'pleaseselectyourcountry': 'براہ کرم اپنا ملک منتخب کریں',
          'pleaseselectyourprovince': 'براہ کرم اپنا صوبہ/ریاست منتخب کریں',
          'pleaseselectyourcity': 'براہ کرم اپنا شہر منتخب کریں',
          'PleasegivestoragePermissiontoapplication':
              'براہ کرم ایپلیکیشن کو اسٹوریج کی اجازت دیں',
          'Somethingwentwrong': 'کچھ غلط ہو گیا ہے'
        }
      };
}
